version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-blog-db
    restart: always
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    ports:
      - "5432:5432"
    volumes:
      - blog_data:/var/lib/postgresql/data

volumes:
  blog_data:
